name: Shared Build Steps

on:
  workflow_call:
    inputs:
      BRANCH:
        description: "branch name."
        type: string
        required: true
      ENVIRONMENT:
        description: "Environment to build to."
        type: string
        required: true



jobs:

  build:
    name: job in shared workflow
    runs-on: ubuntu-latest
    steps:
      - name: step one in shared destroy workflow
        id: step_one
        run: |
          echo "for env we now have ${{ inputs.ENVIRONMENT }} and branch is ${{ inputs.BRANCH }}"
